### ISSUE TITLE
Labels retrieval with tags isn't working with python sdk

### ISSUE THREAD

**Issue by MaEvGoR** [Superb-AI-Suite/spb-cli#71]
Bug: client.get_num_data() with tags still gives all labels (even without tags).

**Environment:**

- maxOS Big Sur v.11.6
- Python 3.8.3
- spb.sdk.__version__ 0.9.0

**Use this code snippet to reproduce:**
```
import spb.sdk

client = spb.sdk.Client()
_, projects = client.get_projects(page=1, page_size=10)
client.set_project(projects[0])

tags = ['dummy_tag_temp']
num_data = client.get_num_data(tags=tags)
print(num_data)
```

Thank you

**Comment by MoonsuCha** [comment]
Thanks for the report. We'll try to check the issue quickly.

**Comment by MoonsuCha** [comment]
We fixed this bug.
